apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: console
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'ghcr.io/cosmonic'
    path: 'cosmonic-control'
    targetRevision: 0.3.0
    chart: cosmonic-control
    helm:
      values: |
        cosmonicLicenseKey: "not-a-valid-license"
        hostName: "https://console.localhost.cosmonic.sh:8443"
        envoy:
          service:
            type: NodePort
            httpNodePort: 30950
  destination:
    name: in-cluster
    namespace: cosmonic-system
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: -1
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
