apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hostgroup
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'ghcr.io/cosmonic'
    path: 'cosmonic-control-hostgroup'
    targetRevision: 0.3.0
    chart: cosmonic-control-hostgroup
  destination:
    name: in-cluster
    namespace: cosmonic-system
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: -1
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
