apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cosmonic-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cosmonic-labs/idp-stack.git
    path: 'manifests/'
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: cosmonic-system
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: -1
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
